### ISSUE TITLE
new transaction file format - Sparkasse

### ISSUE THREAD

**Issue by BlueFoxLa** [FabianReister/home_bank_converter#3]
Hi
can you please make a new transaction file format for the german "Sparkasse"?

In the CSV-Export there is no header like as DKB or VR.

Thanks for this tool!

Best regards
BlueFoxLa

[yyyymmdd-xxxxxxx-umsatz_anonym.CSV.zip](https://github.com/FabianReister/home_bank_converter/files/5832358/yyyymmdd-xxxxxxx-umsatz_anonym.CSV.zip)

**Comment by FabianReister** [comment]
Hi BlueFoxLa! 

Great that you like the tool. I added the "Sparkasse" format. As the header is missing, auto-detecting this format does not work. Therefore, I added a command line argument. In your case, it would be

      python -m home_bank_converter --format sparkasse YOUR_FILE

Please let me know if it works with real data. 

Best regards,
Fabian

**Comment by BlueFoxLa** [comment]
Hi Fabian,

I am sorry for my late answer. But I crashed my data. 

Otherwise, if I want to convert my sparkasse file I got this error message.

__main__.py: error: unrecognized arguments: --format 20200202-4029100-umsatz.CSV

I type the command as you wrote above.

Best regards and stay health!
BlueFoxLa

**Comment by FabianReister** [comment]
Hi BlueFoxLa,

I cannot reproduce your issue. Please make sure that you use the latest version. In case, you installed the python package as described in the instructions, it is required that you execute

`pip install home_bank_converter`

again after pulling the latest changes. 

Best,
Fabian
